[package]
name = "ossuary"
version = "0.5.2-rc"
authors = ["Trevor Bentley <trevor@trevorbentley.com>"]
description = "Library for establishing secure communication channels between two hosts."
keywords = ["communication", "cryptography", "security", "network"]
categories = ["cryptography","network-programming"]
homepage = "https://github.com/mrmekon/ossuary"
repository = "https://github.com/mrmekon/ossuary"
documentation = "https://mrmekon.github.io/ossuary/ossuary/"
readme = "README.md"
license = "Apache-2.0"
edition = "2018"

[badges]
travis-ci = { repository = "mrmekon/ossuary", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
crate_type = ["lib", "cdylib", "staticlib"]

[profile.release]
# Note: opt-level "z" makes it 40% slower and 5% smaller
# opt-level "3" makes it 5% faster and 80% larger
opt-level = "s"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort' #'unwind'
incremental = false
overflow-checks = false

[dependencies]
x25519-dalek = "=0.5.2"
ed25519-dalek = { version = "=1.0.0-pre.1" }
chacha20-poly1305-aead = { version = "=0.1.2" }
rand = "=0.6.5"
